# CMakeLists.txt for App component
idf_component_register(
    SRCS
        "device_model.c"
        "automation.c"
        "wifi_sta.c"
        "mqtt_app.c"
        "mqtt_protocol.c"
        "app_link.c"
        "ble_app.c"
        "selftest.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        BSP
        driver
        esp_wifi
        esp_netif
        esp_event
        mqtt
        json
        nvs_flash
        esp_timer
        bt
)
