idf_component_register(
    SRCS
        "astra/astra_rocket.cpp"
        "astra/ui/launcher.cpp"
        "astra/ui/element/page/item.cpp"
        "hal/hal.cpp"
        "hal/esp32/astra_hal_esp32.cpp"
    INCLUDE_DIRS
        "."
        "astra"
        "hal"
        "hal/esp32"
    REQUIRES
        u8g2
        driver
        esp_timer
)
